/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three";
import React, { JSX, useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Cylinder_1: THREE.SkinnedMesh;
    Cylinder_2: THREE.SkinnedMesh;
    Bone: THREE.Bone;
    hipsL: THREE.Bone;
    hipsL002: THREE.Bone;
    hipsR: THREE.Bone;
    hipsR002: THREE.Bone;
  };
  materials: {
    Material: THREE.MeshStandardMaterial;
  };
};

type ActionName = "TapeDuPied";
type GLTFActions = Record<ActionName, THREE.AnimationAction>;

export function Perso(props: JSX.IntrinsicElements["group"]) {
  const group = useRef<THREE.Group>(null);
  const { nodes, materials, animations } = useGLTF(
    "/models/Untitled.glb"
  ) as unknown as GLTFResult;
  const { actions } = useAnimations(animations, group);
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Armature">
          <group name="Cylinder">
            <skinnedMesh
              name="Cylinder_1"
              geometry={nodes.Cylinder_1.geometry}
              material={nodes.Cylinder_1.material}
              skeleton={nodes.Cylinder_1.skeleton}
            />
            <skinnedMesh
              name="Cylinder_2"
              geometry={nodes.Cylinder_2.geometry}
              material={materials.Material}
              skeleton={nodes.Cylinder_2.skeleton}
            />
          </group>
          <primitive object={nodes.Bone} />
          <primitive object={nodes.hipsL} />
          <primitive object={nodes.hipsL002} />
          <primitive object={nodes.hipsR} />
          <primitive object={nodes.hipsR002} />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/Untitled.glb");
