/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

// fov : field of view
// POLAR ANGLE = part du haut
// savoir si on est sur tablette ou pas : npm install react-responsive, puis query
// avec typsecript c'est un peu relou
// renommer le const exporté dans le fichier transformé, et les chemins vers le fichier glb original
// group pour le scale et la position

import * as THREE from "three";
import React, { useRef, JSX } from "react"; // import le JSX
import { useGLTF, useTexture } from "@react-three/drei";
import { GLTF } from "three-stdlib";
import { EffectComposer, SelectiveBloom } from "@react-three/postprocessing";

type GLTFResult = GLTF & {
  nodes: {
    _________6_blinn1_0: THREE.Mesh;
    body1_blinn1_0: THREE.Mesh;
    cabin_blinn1_0: THREE.Mesh;
    chair_body_blinn1_0: THREE.Mesh;
    comp_blinn1_0: THREE.Mesh;
    emis_lambert1_0: THREE.Mesh;
    handls_blinn1_0: THREE.Mesh;
    keyboard_blinn1_0: THREE.Mesh;
    kovrik_blinn1_0: THREE.Mesh;
    lamp_bl_blinn1_0: THREE.Mesh;
    lamp_white_blinn1_0: THREE.Mesh;
    miuse_blinn1_0: THREE.Mesh;
    monitor2_blinn1_0: THREE.Mesh;
    monitor3_blinn1_0: THREE.Mesh;
    pCylinder5_blinn1_0: THREE.Mesh;
    pillows_blinn1_0: THREE.Mesh;
    polySurface53_blinn1_0: THREE.Mesh;
    radiator_blinn1_0: THREE.Mesh;
    radiator_blinn1_0001: THREE.Mesh;
    railing_blinn1_0: THREE.Mesh;
    red_bttns_blinn1_0: THREE.Mesh;
    red_vac_blinn1_0: THREE.Mesh;
    stylus_blinn1_0: THREE.Mesh;
    table_blinn1_0: THREE.Mesh;
    tablet_blinn1_0: THREE.Mesh;
    triangle_blinn1_0: THREE.Mesh;
    vac_black_blinn1_0: THREE.Mesh;
    vacuum1_blinn1_0: THREE.Mesh;
    vacuumgrey_blinn1_0: THREE.Mesh;
    vires_blinn1_0: THREE.Mesh;
    window_blinn1_0: THREE.Mesh;
    window4_phong1_0: THREE.Mesh;
  };
  materials: {
    blinn1: THREE.MeshStandardMaterial;
    lambert1: THREE.MeshStandardMaterial;
    phong1: THREE.MeshStandardMaterial;
  };
};

// RENOMMER LE NOM DU MODELE
export function Room(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF(
    "/models/optimized-room.glb" // CHANGER LE CHEMIN ICI
  ) as unknown as GLTFResult; // FAIRE LE TYPECASTING unknown ICI SINON TYPESCRIPT PLEURE

  //   // prendre une texture depuis un fichier
  //   const matcapTexture = useTexture("/images/textures/mat1.png");

  //   const bodyMaterial = new THREE.MeshPhongMaterial({
  //     map: matcapTexture,
  //   });

  // Créer un matériau avec une autre couleur
  const curtainMaterial = new THREE.MeshPhongMaterial({ color: "#00ff00" });

  return (
    <group {...props} dispose={null}>
      {/* <EffectComposer>
        <SelectiveBloom
          selection={screensRef.current ? screensRef.current : undefined}
          intensity={2} // Strength of the bloom
          luminanceThreshold={0.2} // Minimum luminance needed
          luminanceSmoothing={0.9} // Smooth transition
          blendFunction={BlendFunction.ADD} // How it blends
        />
      </EffectComposer> */}
      <group userData={{ name: "RootNode" }}>
        <group userData={{ name: "radiator" }}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.radiator_blinn1_0.geometry}
            material={materials.blinn1}
            userData={{ name: "radiator_blinn1_0" }}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.radiator_blinn1_0001.geometry}
            material={materials.blinn1}
            userData={{ name: "radiator_blinn1_0.001" }}
          />
        </group>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes._________6_blinn1_0.geometry}
          material={curtainMaterial} // on applique le matériau custom ici
          userData={{ name: "_________6_blinn1_0" }}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.body1_blinn1_0.geometry}
          material={materials.blinn1}
          userData={{ name: "body1_blinn1_0" }}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.cabin_blinn1_0.geometry}
          material={materials.blinn1}
          userData={{ name: "cabin_blinn1_0" }}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.chair_body_blinn1_0.geometry}
          material={materials.blinn1}
          userData={{ name: "chair_body_blinn1_0" }}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.comp_blinn1_0.geometry}
          material={materials.blinn1}
          userData={{ name: "comp_blinn1_0" }}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.emis_lambert1_0.geometry}
          material={materials.lambert1}
          userData={{ name: "emis_lambert1_0" }}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.handls_blinn1_0.geometry}
          material={materials.blinn1}
          userData={{ name: "handls_blinn1_0" }}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.keyboard_blinn1_0.geometry}
          material={materials.blinn1}
          userData={{ name: "keyboard_blinn1_0" }}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.kovrik_blinn1_0.geometry}
          material={materials.blinn1}
          userData={{ name: "kovrik_blinn1_0" }}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.lamp_bl_blinn1_0.geometry}
          material={materials.blinn1}
          userData={{ name: "lamp_bl_blinn1_0" }}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.lamp_white_blinn1_0.geometry}
          material={materials.blinn1}
          userData={{ name: "lamp_white_blinn1_0" }}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.miuse_blinn1_0.geometry}
          material={materials.blinn1}
          userData={{ name: "miuse_blinn1_0" }}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.monitor2_blinn1_0.geometry}
          material={materials.blinn1}
          userData={{ name: "monitor2_blinn1_0" }}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.monitor3_blinn1_0.geometry}
          material={materials.blinn1}
          userData={{ name: "monitor3_blinn1_0" }}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCylinder5_blinn1_0.geometry}
          material={materials.blinn1}
          userData={{ name: "pCylinder5_blinn1_0" }}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pillows_blinn1_0.geometry}
          material={materials.blinn1}
          userData={{ name: "pillows_blinn1_0" }}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.polySurface53_blinn1_0.geometry}
          material={materials.blinn1}
          userData={{ name: "polySurface53_blinn1_0" }}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.railing_blinn1_0.geometry}
          material={materials.blinn1}
          userData={{ name: "railing_blinn1_0" }}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.red_bttns_blinn1_0.geometry}
          material={materials.blinn1}
          userData={{ name: "red_bttns_blinn1_0" }}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.red_vac_blinn1_0.geometry}
          material={materials.blinn1}
          userData={{ name: "red_vac_blinn1_0" }}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.stylus_blinn1_0.geometry}
          material={materials.blinn1}
          userData={{ name: "stylus_blinn1_0" }}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.table_blinn1_0.geometry}
          material={materials.blinn1}
          userData={{ name: "table_blinn1_0" }}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.tablet_blinn1_0.geometry}
          material={materials.blinn1}
          userData={{ name: "tablet_blinn1_0" }}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.triangle_blinn1_0.geometry}
          material={materials.blinn1}
          userData={{ name: "triangle_blinn1_0" }}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.vac_black_blinn1_0.geometry}
          material={materials.blinn1}
          userData={{ name: "vac_black_blinn1_0" }}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.vacuum1_blinn1_0.geometry}
          material={materials.blinn1}
          userData={{ name: "vacuum1_blinn1_0" }}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.vacuumgrey_blinn1_0.geometry}
          material={materials.blinn1}
          userData={{ name: "vacuumgrey_blinn1_0" }}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.vires_blinn1_0.geometry}
          material={materials.blinn1}
          userData={{ name: "vires_blinn1_0" }}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.window_blinn1_0.geometry}
          material={materials.blinn1}
          userData={{ name: "window_blinn1_0" }}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.window4_phong1_0.geometry}
          material={materials.phong1}
          userData={{ name: "window4_phong1_0" }}
        />
      </group>
    </group>
  );
}
// CHANGER LE CHEMIN ICI
useGLTF.preload("/models/optimized-room.glb");
